<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DraftSimulator.Core\DraftSimulator.Core.csproj" />
    <ProjectReference Include="..\DraftSimulator.Protocol\DraftSimulator.Protocol.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Ini" Version="10.0.12" />
    <PackageReference Include="SkiaSharp" Version="2.88.9" />
    <PackageReference Include="Steamworks.NET" Version="2024.8.0" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
      <_Parameter1>SteamAppId</_Parameter1>
      <_Parameter2>$(SteamAppId)</_Parameter2>
    </AssemblyAttribute>
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
